name: Release
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:
    
jobs:
  newrelic:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"