name: New Relic Account Creation
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:
    
jobs:
  create_newrelic_account:
    runs-on: ubuntu-latest
    steps:
      - name: Create New Relic Account
        env:
          NEW_RELIC_API_KEY: ${{ secrets.NEW_RELIC_API_KEY }}
        run: |
          curl -X POST \
            -H "X-Api-Key:${{ env.NEW_RELIC_API_KEY }}" \
            -d 'account_name=example_account' \
            'https://api.newrelic.com/v2/accounts.json'